### ISSUE TITLE
How to get `hooks` `socketio` etc from `feathers` object

### ISSUE THREAD

**Issue by osenvosem** [feathersjs/feathers-client#118]
According the documentation `hooks` or `rest`should be available on `feathers` object, but there is no any. I'm using it with webpack:

```js
const feathers = require('feathers/client'); or just ('feathers');

feathers.rest === undefined
feathers.hooks === undefined
```
What am I doing wrong?

**Comment by daffl** [comment]
You are using `feathers/client` this is the `feathers-client` module (`const feathers = require('feathers-client')`). As the Readme says:

> While Feathers and its modules can be used on the client with an NPM compatible module loader like Browserify, Webpack or StealJS, feathers-client consolidates a standard set of client plugins into a single distributable that can be used standalone in the browser or with other module loaders (like RequireJS) that don't support NPM.

This means you should only use it if you don't use a module loader that supports NPM.

**Comment by osenvosem** [comment]
@daffl so with webpack I suppose to import client modules separately and can't use `feathers-client` module? like so:
```js
const feathers = require('feathers/client');
const rest = require('feathers-rest/client');
const auth = require('feathers-authentication/client');
etc...
```
It seems a little confusing.

**Comment by daffl** [comment]
Yes, that's how it is documented in https://docs.feathersjs.com/clients/feathers.html#usage-in-nodejs-and-client-module-loaders

**Comment by daffl** [comment]
You can still use the feathers-client module if you want.

**Comment by osenvosem** [comment]
@daffl thank you for the answers.
One more thing: I got an error in browser every time I am trying to configure `rest`:

```
Uncaught TypeError: fn.call is not a function(…)
```
It leads here:
![screen shot 2016-11-24 at 20 08 57](https://cloud.githubusercontent.com/assets/6762673/20606428/e0109332-b281-11e6-977d-8c1cb371804b.png)

The code:
```js
const feathers = require('feathers/client');
const rest = require('feathers-rest/client');
const hooks = require('feathers-hooks');


const client = feathers()
  .configure(hooks())
  .configure(rest());
```

**Comment by daffl** [comment]
Probably a Webpack configuration issue somewhere. It worked when I tried it.
