### ISSUE TITLE
npm package is broken.

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-client#12]
0.3.0 on npm still has a `dist` folder instead of the `src` and `lib` folders that the npm scripts are looking for.

![screen shot 2015-11-25 at 9 01 43 pm](https://cloud.githubusercontent.com/assets/128857/11414841/c629c4e6-93b7-11e5-8465-9bb208fdbb68.jpg)

@daffl Can you add me to the npm package?

**Comment by daffl** [comment]
Already just did for #11. `dist/` should be there for Browser clients though. I'm not sure why `lib` isn't being published though.

**Comment by daffl** [comment]
I bet it's because the prepublish script (`"prepublish": "npm run compile"`) is missing.

**Comment by marshallswain** [comment]
Yep.  That was it.

**Comment by marshallswain** [comment]
Opening this back up.  It's not working with Steal in it's current condition.

![screen shot 2015-11-25 at 9 33 22 pm](https://cloud.githubusercontent.com/assets/128857/11415136/32f7cd44-93bc-11e5-944c-dfd1977b775f.jpg)
