### ISSUE TITLE
Socket.io timeout does nothing when there is JWT token available

### ISSUE THREAD

**Issue by Creiger** [feathersjs/feathers-client#129]
### Steps to reproduce

When the feathers server is not running and there is already a JWT token stored in client cookies, this function 

`app.authenticate().then(showApplication,` showLogin);

never fires anything. It does not throw any error also. When i delete JWT token, showLogin function is fired.

### Expected behavior
I think this should throw an error after socket.io timeout set in app configuration.

### Actual behavior
Does nothing.

**Comment by marshallswain** [comment]
Thanks @Creiger I'm moving this to the `feathers-authentication-client` repo.

**Comment by marshallswain** [comment]
Issue moved to [feathersjs/feathers-authentication-client #19](https://github.com/feathersjs/feathers-authentication-client/issues/19) via [**ZenHub**](https://www.zenhub.com/)
