### ISSUE TITLE
Authentication should be removed

### ISSUE THREAD

**Issue by elfey** [feathersjs/feathers-client#136]
With the new `feathers-authentication-client`, authentication isn't really necessary in this module. This module is now, for the most part, kind of a "networking" module for connecting the client to the server (as opposed to authenticating).

So it would make sense that we remove the authentication bit from this module. (i.e. `feathersClient.authentication` because it's being replaced with `feathers-authentication-client`).

**Comment by marshallswain** [comment]
@mz103 the intention of this module was originally to provide all client modules in one place.  All other modules would be at `feathers-module/client`.

**Comment by daffl** [comment]
I think we will keep it like this for now (`feathers-authentication-client` will still be `feathers.authentication`). It will all make more sense in the next version when we tackle #137. I still don't know how I feel about browser builds for each individual client module but maybe that is the best way to do it to avoid any more confusion on what is included in the client build.

**Comment by marshallswain** [comment]
Closing this for now.
