### ISSUE TITLE
Bundled feathers.js - Socket Authentication with Local Strategy Always Times Out

### ISSUE THREAD

**Issue by robotlandman** [feathersjs/feathers-client#155]
### Steps to reproduce
Client-side Gist: [https://gist.github.com/robotlandman/4e7feb3ec15a964250ab2941dc8cc7bb](https://gist.github.com/robotlandman/4e7feb3ec15a964250ab2941dc8cc7bb)

I'm using the unified feathers-client from here:
[https://github.com/feathersjs/feathers-client/blob/master/dist/feathers.js](https://github.com/feathersjs/feathers-client/blob/master/dist/feathers.js)

### Expected behavior
client.authenticate() should redirect to the successful login page as specified in my login.js file or display an error if authentication is unsuccessful.

### Actual behavior
The feathers-client socket timeout handler is hit in both cases - on successful authentication and user not found. The response is always: "Error: Authentication timed out" after the default 5 seconds.

I see the server reply on the socket right away (in the code I'm listening for 'authenticated' and 'unauthorized' socket events for testing) with the correct response, including the token when authentication is successful. The feathers-client ignores these responses and doesn't store the token in localStorage on successful authentication.

Here are the web browser console outputs for the socket events to confirm the authentication is happening as expected on feathers server-side:
**Successful authentication**
`Socket authenticated: {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiJiNFBRTllDNkZlMjlhN1ZLIiwiaWF0IjoxNDkwMTAxOTIyLCJleHAiOjE0OTAxODgzMjIsImlzcyI6ImZlYXRoZXJzIn0.Uys3gyHUDV_78B0JRzcqmOYvzbqyJ9lPd7e1JlbggMI","data":{"email":"admin@local","roles":["admins"],"_id":"b4PQNYC6Fe29a7VK"}}`

**User not found**
`Socket unauthorized: {"name":"NotAuthenticated","message":"Invalid login.","code":401,"className":"not-authenticated","errors":{}}`

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
**Server-Side**
feathers@2.1.1
feathers-commons@0.8.7
feathers-authentication@0.7.12
feathers-configuration@0.3.3
feathers-errors@2.6.2
feathers-hooks@1.8.1
feathers-hooks-common@2.0.3
feathers-nedb@2.6.1
feathers-query-filters@2.1.2
feathers-rest@1.7.1
feathers-socketio@1.5.2
feathers-socket-commons@2.4.0

**Client-Side**
Whatever is bundled in the latest feathers-client/dist/feathers.js file - not sure how you tell the version?

**NodeJS version**:
v6.10.0

**Operating System**:
Server: Ubuntu 16.04
Client: Windows 10

**Browser Version**:
Chrome 56.0.2924.87
Firefox 52.0.1

**React Native Version**:
N/A

**Module Loader**:
N/A

**Comment by daffl** [comment]
You should not link to the master dist but to a [specific version](https://github.com/feathersjs/feathers-client/releases) (which is what we are showing in the documentation). The current master requires `feathers-authentication` 1.0.0 on the server (and linking to it directly *will* break your app in the future).

As shown in the [client documentation](https://docs.feathersjs.com/clients/feathers.html#feathers-client) you can link to the latest backwards compatible 1.x version of this package using Unpkg like this:

```js
<script type="text/javascript" src="//unpkg.com/feathers-client@^1.0.0/dist/feathers.js"></script>
```

**Comment by robotlandman** [comment]
I figured I was doing something wrong. That was it - thanks!
