### ISSUE TITLE
how to use in typescript

### ISSUE THREAD

**Issue by gmchaturvedi1** [feathersjs/feathers-client#17]
dear Friends kindly suggest how to use this library in client side with typescript i am using angular2

**Comment by daffl** [comment]
Did you try? I saw some people use it with TypeScript and it should work the same as described in the documentation.

**Comment by ekryski** [comment]
Given that we have no response from @gmchaturvedi1 to see what the problem is and the fact that none of us use typescript I'm going to close this for now.
