### ISSUE TITLE
Drop socket.io

### ISSUE THREAD

**Issue by stevenvachon** [feathersjs/feathers-client#177]
Not everyone needs to support browsers that don't support WebSocket (`>= IE9`).

**Comment by daffl** [comment]
On the client Socket.io itself will always have to be included manually. If you do not want to include `feathers-socketio/client` you can always [use it with a client side module loader](https://docs.feathersjs.com/api/client.html#node-and-npm-loaders).

**Comment by stevenvachon** [comment]
My proposal is to not depend on socket.io by default. Forcing it to be included is still very opinionated.

**Comment by marshallswain** [comment]
It's not forced to be included.  You can use Primus or any of the feathers-rest clients libs.

**Comment by marshallswain** [comment]
Oh.  I think I see what's going on.  @stevenvachon you can use the individual client libs if you don't want socket.io.  This feathers-client package is just a convenient wrapper to include all libs.
