### ISSUE TITLE
Feathers Authentication returning NotFound: Page not found

### ISSUE THREAD

**Issue by maseruka** [feathersjs/feathers-client#188]
### Expected behavior

authenticate with username and password that exists in my DB and return token

### Actual behavior

running 

```js
function localAuth() {
  app.authenticate({
    type:  'local',
    email: 'feathers@example.com',
    password:  'secret'
  }).then(token =>  {
    console.log('User is  logged  in with token : '+token);
  }).catch(err => {
    console.log('Failed : '+err);
  });
}
```

returns "Failed : Not found: page not found"

### System configuration

I just generated the app haven't added any custom code on the backend (everything was done by the generator), only working with the frontend

**Module versions** (especially the part that's not working):

Everything Latest, just installed it yesterday

**NodeJS version**:
v7.10.0
**Operating System**:
Ubuntu 16.04
**Browser Version**:
Firefox 53.0
**React Native Version**:

**Module Loader**:
Nothing, just pure js

Repo : https://github.com/maseruka/feathers-app

**Comment by daffl** [comment]
Are you sure you selected `local` authentication when prompted? The default is no selection so if you just hit enter nothing will be set up.

**Comment by maseruka** [comment]
i did, you can check in the repo

**Comment by daffl** [comment]
Ah sorry, I totally missed the repo link. I'm not sure where you got the `feathers.js` file in the `public/` folder from but it looks like an older incompatible version. If you get the 2.x version from https://github.com/feathersjs/feathers-client/tree/c61d3fce734f2cc5b230ee76413f74b86e5463d8/dist it will work.

**Comment by maseruka** [comment]
Or yeah, i had picked an older version from unpkg.com cdn (The cdns included in the docs are outdated.  https://docs.feathersjs.com/guides/step-by-step/basic-feathers/rest-client.html ), think you can also fix that in the docs, thanks for the help

**Comment by daffl** [comment]
You are right, those were the wrong links. All fixed now, thank you.
