### ISSUE TITLE
$sort does not work for find()

### ISSUE THREAD

**Issue by evanbarter** [feathersjs/feathers-client#19]
Crux of the issue is querystring can't stringify objects so the $sort object is never added to the URL params.

Looking in to alternatives, https://github.com/sindresorhus/query-string mentions the following, but gave me enough to workaround the issue while still using querystring:
>This module intentionally doesn't support nesting as it's not spec'd and varies between implementations, which causes a lot of edge cases.

>You're much better off just converting the object to a JSON string:
```js
queryString.stringify({
	foo: 'bar',
	nested: JSON.stringify({
		unicorn: 'cake'
	})
});
//=> 'foo=bar&nested=%7B%22unicorn%22%3A%22cake%22%7D'
```

Using this method to pass $sort also requires a before find hook server-side to parse the param so I don't think this is ideal.

https://github.com/ljharb/qs does support nested objects and would stringify $sort as $sort[field]=1

**Comment by ekryski** [comment]
Dammit! Thanks for reporting @evanbarter. We might (hopefully) just need to swap the lib. Do you mind trying it out with https://github.com/ljharb/qs and submitting a PR?

**Comment by daffl** [comment]
This is going to be tested and fixed in the new `feathers-rest` module via https://github.com/feathersjs/feathers-rest/pull/1

**Comment by evanbarter** [comment]
Thanks, sorry I didn't get a chance to test out qs but it looks like that's been addressed now :+1:

**Comment by daffl** [comment]
All good. Thanks for reporting and doing the research. That helped to get the test and fix for that in quickly.

**Comment by ekryski** [comment]
Now that https://github.com/feathersjs/feathers-rest/pull/1 landed and since feathers is now isomorphic feathers-2.0.0.pre-2 fixes this.
