### ISSUE TITLE
Do you need feathers setup on the server to use feathers on the client?

### ISSUE THREAD

**Issue by die20** [feathersjs/feathers-client#196]
Hey, I have a quick question. 

Do you need to have a feathers socket server to use feathers client socket.io? Or can you connect to a socket.io server from a feathers socket.io client?

**Comment by daffl** [comment]
Yes, you can use Feathers on the client and implement any kind of custom service that e.g. talks to another REST API or another Socket (see [this article](https://blog.feathersjs.com/using-feathersjs-to-make-your-existing-api-real-time-813f7c3fd892) for examples).

The question is what kind of Socket API you are looking at. We don't know about many standardized Socket APIs so I think it might make more sense to proxy your API as a service on a Feathers server and access it the same way as any others on the client.
