### ISSUE TITLE
Add hook support

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-client#20]
It should be possible to get [feathers-hooks](https://github.com/feathersjs/feathers-hooks/) working with the client. This means that you can add hooks to pre- and postprocess your data before sending them to the API and also add behaviours like offline capabilities and caching.

**Comment by marshallswain** [comment]
Ooh.  This is a REALLY good idea!  :+1:

**Comment by ahdinosaur** [comment]
yes please, in my case i'd like to use [feathers-tcomb](https://github.com/ahdinosaur/feathers-tcomb), which relies on hooks, for validation within the client before requests are sent. :+1:

**Comment by ekryski** [comment]
I think now that feathers is becoming isomorphic this is now solved in 2.0.0.pre-2.
