### ISSUE TITLE
npm packages are installed even if they already exist when creating a new sequelize mysql service

### ISSUE THREAD

**Issue by delebash** [feathersjs/feathers-client#209]
### Steps to reproduce

feathers g service
choose sequalize
choose mysql

### Expected behavior
packages should only be installed once

### Actual behavior
Every time you add a new service npm tries to reinstall packages mysql2 and sequalize even if they are already installed

### System configuration

**Module versions** (especially the part that's not working):
feathers cli 2.3.8
**NodeJS version**:
8.6.0
**Operating System**:
window 10 x64

**Comment by daffl** [comment]
This is how Yeoman and Yarn/npm seem to behave and we decided not to try and work around it. See https://github.com/feathersjs/generator-feathers/issues/242 for the full discussion.
