### ISSUE TITLE
REST base.js missing ${options.base} leads to broken relative url

### ISSUE THREAD

**Issue by wuyuanyi135** [feathersjs/feathers-client#21]
Problematic source: https://github.com/feathersjs/feathers-client/blob/master/src/rest/base.js
```
    var app = feathers().configure(feathers.jquery());
    var tempSwitchService = app.service('api/temp/switch');

    tempSwitchService.find().then(function(temp) {
      console.log(temp);
    });
```

Error: `GET http://api/temp/switch net::ERR_NAME_NOT_RESOLVED`

The missing ${options.base} causes the string template starting with slash, breaking a relative url. My workaround is assign base manually

```
    var app = feathers().configure(feathers.jquery());
    var tempSwitchService = app.service('api/temp/switch');
+   app.base='';
    tempSwitchService.find().then(function(temp) {
      console.log(temp);
    });
```

Suggestion: place no slash if options.base is absent.

**Comment by daffl** [comment]
Thank you! https://github.com/feathersjs/feathers-client/blob/master/src/rest/base.js#L16 should probably read

```js
if(options.base) {
  this.base = `${options.base}/${this.name}`;
  delete this.options.base;
} else {
  this.base = this.name;
}
```

Would you mind submitting the change in a pull request? I can get a release out right away.
We're also working on a new version of a fully isomorphic Feathers client but I think it has the same problem at the moment.

**Comment by wuyuanyi135** [comment]
:+1:
