### ISSUE TITLE
Support offline mode

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-client#29]
It would be really ballin' to detect if the user has an internet connection. If they don't, store actions in a local store and then emit events back to the server when they regain a connection.

You'd probably also need to refresh all your data to make sure you have the same state as the server in the event that other users updated data you care about while you were offline.

**Comment by luizbills** [comment]
:+1:

**Comment by Koulwa** [comment]
Would love to see this feature as well. :) But from what i've found of feathersjs, i'm excited to say the least.

**Comment by katopz** [comment]
Just referrer https://github.com/feathersjs/feathers/issues/264

**Comment by hnordt** [comment]
I think it should not be Feathers concern. It a behaviour that is very tied to frontend app.

For example, if I'm using Flux, it's straightforward to support offline apps:

```js
const initialState = {
  users: [].
  pending: []
}

function reducer(state = initialState, action) {
  if (action.type === SAVE_USER_SUCCESS) {
    return {  ...state, users: [...users, action.payload] }
  }
  if (action.type === SAVE_USER_FAILURE) {
    return {  ...state, pending: [...pending, action] }
  }
  return state
}

function saveUser(data) {
  return dispatch => {
    userService.update(data)
      .then(() => dispatch(saveUserSuccess())
      .catch(() => dispatch(saveUserFailure(data))
  }
}

function saveUserSuccess() {
  return {
    type: SAVE_USER_SUCCESS
  }
}

function saveUserFailure(data) {
  return {
    type: SAVE_USER_FAILURE,
    payload: data
  }
}
```

**Comment by ekryski** [comment]
@hnordt like everything else it would be entirely optional but we have some ideas about how we can make this work really well and potentially be an alternative to Flux/Redux/Relay, while still keeping it fairly lightweight.

You are definitely correct though, the developer should be in control of which data is cached and how it is cached because that is going to be application specific.

**Comment by hnordt** [comment]
I liked the first idea. I'll experiment some approaches too and I'll share the results.

**Comment by tiyindyfee** [comment]
At Google I/O this year there was a talk about offline apps using service workers. I was impressed by how well this approached worked and think it may be the future of running web apps offline. The talk didn't go into deep detail, but their approach is open source. Definitely worth a watch and might apply to how offline is engineered in Feathers: https://www.youtube.com/watch?v=cmGr0RszHc8

Here's the source code for Google's offline service workers: https://github.com/GoogleChrome/ioweb2016/tree/master/app/scripts/sw-toolbox

**Comment by marshallswain** [comment]
Cool.  Thanks for sharing @tiyindyfee!

**Comment by ecerroni** [comment]
@ekryski Any ETA about this feature?

**Comment by simonbdev** [comment]
+1

**Comment by alvirtuoso** [comment]
+1
Has anyone looked into or used offlinejs? It claims to detect online connection and caches REST calls then handle them automatically when back online

**Comment by myuseringithub** [comment]
I think feathers should be separated into small modules and let the developer choose and pick which they like. Just like the concept of Koa middleware. And ofcourse have a list for the official repositories, separate from those that are third-party. 
Don't make another bulky FRAMEWORK ☠️

**Comment by daffl** [comment]
That's exactly what Feathers already does (a list of official and unofficial plugins can be found [here](https://docs.feathersjs.com/v/auk/ecosystem/)). I'm not sure what you are suggesting?

**Comment by marshallswain** [comment]
@myuseringithub It most absolutely is a genius idea, though!  Great minds think alike.  😉

**Comment by marshallswain** [comment]
@myuseringithub I see now that Koa support is your actual goal.  We'll help wherever possible if you want to create an adapter for it.

**Comment by alainrodriguezz** [comment]
Is this feature still on the table? :)

**Comment by eddyystop** [comment]
Yes, some work is being done on it.

**Comment by daffl** [comment]
As @eddyystop is doing a lot of great work in this department I think we can close this. See https://docs.feathersjs.com/guides/offline-first/readme.html and the `offline` repositories in the organization.

**Comment by teddy-error** [comment]
For those coming to this issue from [the documentation](https://docs.feathersjs.com/guides/about/vs.html) there is now [offline support](https://docs.feathersjs.com/guides/offline-first/readme.html).

**Comment by ramstein74** [comment]
Please update the docs
https://feathersjs.com/feathers-vs-firebase

**Comment by daffl** [comment]
The website is editable by anybody directly (e.g. https://github.com/feathersjs/website/edit/master/content/feathers-vs-firebase.html).
