### ISSUE TITLE
Socket.io timeouts?

### ISSUE THREAD

**Issue by JoshZA** [feathersjs/feathers-client#42]
```
app.authenticate({
    type: 'local',
    'email': 'admin@feathersjs.com',
    'password': 'admin'
}).then(function(result){
    console.log('Authenticated!', app.get('token'));
}).catch(function(error){
    console.error('Error authenticating!', error);
});
```

Win 10 with node v5.10.0

SocketIo only, no rest plugin loaded

When I run this, and there's no feathers server running - the Catch handler never fires, code just runs infinitely

Surely, there should be some default timeout for this?

**Comment by daffl** [comment]
Related: https://github.com/feathersjs/feathers-socket-commons/issues/9.

**Comment by daffl** [comment]
Socket client timeouts are now implemented and set to 5000ms by default. They can be configured with `app.configure(socketio(socket, { timeout: 2000 })`
