### ISSUE TITLE
Refresh browser

### ISSUE THREAD

**Issue by ryuken** [feathersjs/feathers-client#68]
Hi, I have a problem with feathers-client when I refresh the browser page and the backend is restricted for authenticated users. The client will give an error that the authentication token is missing. My home page isn't restricted, so when I go to my home page and navigate from there everything is fine.

When I do a AJAX request via jQuery with { token : localStorage.getItem("feathers-jwt") } I get no error (even on browser refresh)

Does the client handle browser refresh in a weird way or something?

**Comment by daffl** [comment]
If you hit a restricted endpoint with the browser without setting the `Authorization` header it will definitely show an authentication error. If you are using PushState you have to make sure that every route returns the unrestricted `index.html`.

**Comment by ryuken** [comment]
Thanks for your reply. Why would I need to set the Authorization header?
The feathersjs-client does that right? The problem is that on browser refresh the token will not be set (while the token is in the localStorage). I use feathersjs-client in React. When I replace the part which does the request to find data with a plain jQuery ajax request it works. So this is done when components are rendered, so the token is available from the localStorage. But strangely the feathersjs-client doesn't set it in this scenario. I also tried to set it manually but I couldn't figure out how to pass that.

**Comment by daffl** [comment]
You have to call `app.authenticate()` (with no parameters) first to let the client know that it should use the store token for future requests.

**Comment by ryuken** [comment]
Thanks! I already did that for checking if the user is authenticated, but now I wrapped it around my service call and then it works on browser refresh. Is that the way you meant?

PS: I'm using React, Redux and created an action which does the app.authenticate() and stores the result in the redux store and then I checked this variable when a page needs authentication

**Comment by daffl** [comment]
Yes, you have to wait for the promise from `app.authenticate()` to return before making any service calls.

**Comment by ryuken** [comment]
Cool then its clear for me thanks!

**Comment by L3V147H4N** [comment]
I'm trying exactly this method but it seems that even after the authentication response the request is not authenticated, it seems that it takes some small time to set it up.
If I .authenticate() and in the .then I put a setTimeout for 200 milliseconds for ex. it works, but it doesn't if I call the service instantly
