### ISSUE TITLE
Use Promises

### ISSUE THREAD

**Issue by makrolabs** [feathersjs/feathers-client#7]
todoService.create({
      text: 'A todo',
      complete: false
    }, function(error, todo) {
      console.log('Success');
    });

Should be:

    todoService.create({
      text: 'A todo',
      complete: false
    }).then(function (todo) {
      console.log('Success');
    });

**Comment by daffl** [comment]
It should indeed. I'm working on 0.3.0 which will be migrated to ES6, support batches (https://github.com/feathersjs/feathers-batch) and promises.

**Comment by daffl** [comment]
This is available in the 0.3.0 release. The plugin has also been migrated to ES6.
