### ISSUE TITLE
SocketIO timeout based on service

### ISSUE THREAD

**Issue by Mangatt** [feathersjs/feathers-client#84]
Hi,
is it possible to change default 5000ms timeout on SocketIO based on service? 5 seconds are enough for most services, but we need to lift this one specifically on /uploads since those can take more than that.

**Comment by daffl** [comment]
You should be able to set the `timeout` property on each service to get individual timeouts:

```js
app.service('uploads').timeout = 30000;
```

**Comment by Mangatt** [comment]
Great, thanks a lot. It would be nice if this could be part of documentation or at least part of Upload file guide.

**Comment by marshallswain** [comment]
It looks like it's part of the docs here: http://docs.feathersjs.com/clients/socket-io.html

**Comment by Mangatt** [comment]
Yes, there is timeout mentioned, but not a word about usage based on service as @daffl posted here. That's why I posted this issue, since I thought that this is not possible.

**Comment by marshallswain** [comment]
Good point. I created an issue for this: https://github.com/feathersjs/feathers-docs/issues/220

**Comment by daffl** [comment]
If someone wants to add this, editing https://github.com/feathersjs/feathers-docs/edit/master/clients/socket-io.md should only take a minute or two 😄

**Comment by vodniciarv** [comment]
`app.service('uploads').timeout = 30000;`

now, this code don't work

**Comment by vodniciarv** [comment]
proprety `timeout` is undefined

**Comment by daffl** [comment]
This only available in Websocket client services.
