### ISSUE TITLE
feathers client and requireJS

### ISSUE THREAD

**Issue by MarcGodard** [feathersjs/feathers-client#85]
Hi I am loading feathersJS client into an app that uses requireJS and I am getting errors.

Error:
```
require.js:143 Uncaught Error: Module name "events" has not been loaded yet for context: _. Use require([])
```

How I am loading it:
```
paths: {
         feathers_client: "../libs/feathers-client/dist/feathers",
         ...
}
```

Then I just do like any other require module.

Am I missing something?

**Comment by daffl** [comment]
I thought the Browserify `--standalone` option create a RequireJS compatible build but you may have to `shim` it as a global:

```js
shim: {
  feathers_client: {
  exports: "feathers"
}
```

**Comment by MarcGodard** [comment]
I will try this tomorrow. Thanks.

**Comment by MarcGodard** [comment]
Same error. As soon as I require feathers in a module (even with the shim).

Has feathers been used with steals? I might try that if you know it will work.

**Comment by fedevela** [comment]
@MarcGodard Can't webpack do what you need to get done? I have gotten that to work with feathers seamlessly.

**Comment by daffl** [comment]
So does Browserify and StealJS. Nevertheless it should still work with RequireJS.

**Comment by daffl** [comment]
So apparently I made this comment in the wrong issue so here again: It looks like the RequireJS problem can be fixed with https://github.com/rse/browserify-derequire so I'll give that a try later today.

**Comment by MarcGodard** [comment]
@fedevela never used webpack but this is an already existing large program.

@daffl Will look into that. I hope its available with bower, because again, old large program that I am slowly updating. However, if you can tell me if you have seen it work nicely with stealsJS I will do that conversion next.

**Comment by MarcGodard** [comment]
I looked into the derequire, and this makes the package even more complicated. I will just skip feathers for now and use my regular server API. Thanks for all your help.

**Comment by daffl** [comment]
It looks like the trick is to use the `require` format like this:

```js
define(function (require) {
    var feathers = require('feathers');
```

I put a working example based on the [create-template](https://github.com/volojs/create-template)  at https://github.com/daffl/create-template.
