### ISSUE TITLE
documentation on how to build client

### ISSUE THREAD

**Issue by jiangts** [feathersjs/feathers-client#87]
I'm using ClojureScript which only consumes UMD builds. I only want a subset of the modules packaged here, and couldn't find any docs on how to build a UMD package. All help appreciated! I'm still a noob with browserify/webpack.

**Comment by daffl** [comment]
It should be fairly straightforward by doing

```
git clone git@github.com:feathersjs/feathers-client.git
cd feather-client
npm install
```

Then modify https://github.com/feathersjs/feathers-client/blob/master/src/client.js to the imports you need and run

```
npm run browserify
```

The compiled files which already include the UMD format will be in the `dist/` folder.

**Comment by daffl** [comment]
Feathers works with StealJS (in which case I'd recommend importing only the plugins you need instead of the entire client).

It also looks like the RequireJS problem can be fixed with https://github.com/rse/browserify-derequire so I'll give that a try later today.
