### ISSUE TITLE
How to destroy feathers and socketio client?

### ISSUE THREAD

**Issue by StanleyAM** [feathersjs/feathers-client#95]
Hi, my feathers setup code is like below:
```
var socketio = io("http://ip-A");
var app = feathers()
    .configure(feathers.hooks())
    .configure(feathers.socketio(socketio));
```
Now I want to close "ip-A" (Service A) connection and establish "ip-B" (Service B) connection.
How can I destroy feathers and socketio client for the Service A? Thanks.

**Comment by marshallswain** [comment]
So you want to be able to swap the socket out in existing services?

```js
// Points to http://ip-A/todos
var todoService = app.service('todos');

// ...Swap out the socket somehow...

// Now it points to http://ip-B/todos
todoService.find()
```

Am I understanding correctly what you want there?  All service stay in place, we just point the socket to another location?

**Comment by daffl** [comment]
The best way is probably to create a new app with the new connection. A somewhat hacky way would be to remove all existing services (since they will have a reference to the old connection and set `app.io` to the new socket:


```js
app.services = {};
app.io = otherSocket;
```

**Comment by marshallswain** [comment]
You can actually keep a reference to your socket and modify the Manager instance.  I just tested this out and it works:

```js
import feathers from 'feathers/client';
import hooks from 'feathers-hooks';
import socketio from 'feathers-socketio/client';
import io from 'socket.io-client/socket.io';

var socket = io("http://ip-A");
var app = feathers()
    .configure(hooks())
    .configure(socketio(socket));

setTimeout(() => {
  socket.disconnect();
  socket.io.uri = 'http://ip-B';
  socket.connect();
}, 5000);
```

So you can just call `disconnect()`, swap out the `socket.io.uri`, and call `connect()`.

**Comment by StanleyAM** [comment]
Hi @daffl and @marshallswain,

Thanks to your reply. That is what I want.
Very appreciative of your help. Thanks.
