### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by jiangts** [feathersjs/feathers-client#96]
I hate to be that guy, but what's browser support looking like for feathers-client?

**Comment by marshallswain** [comment]
It really only depends on the transport you use.  If you're using `feathers-socket.io` you look at socket.io's browser compatibility.  `feathers-rest` has several supported xhr packages (see here: https://docs.feathersjs.com/clients/feathers.html).  Primus supports 8 possible engines.  So you'd need to investigate the underlying package to get your answer.

**Comment by jiangts** [comment]
wonderful, thanks!

**Comment by daffl** [comment]
Basically all current versions of Chrome, Firefox and Safari and IE 9+ should work (as long as the polyfill is included).

@marshallswain We might want to set up Saucelabs for this repository to run the tests against that and get the browser matrix badge.

**Comment by daffl** [comment]
Follow up issue is #97

**Comment by daffl** [comment]
All done now with automated tests in all browsers:

[![Sauce Test Status](https://saucelabs.com/browser-matrix/feathersjs.svg)](https://saucelabs.com/u/feathersjs)
